version: "3.9"

services:

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api-service
    networks:
      - appnet

  api-service:
    build:
      context: ./api-service
      dockerfile: ../docker/go-service/Dockerfile
    container_name: api-service
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    networks:
      - appnet

  api-worker:
    build:
      context: ./api-worker
      dockerfile: ../docker/go-service/Dockerfile
    container_name: api-worker
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    networks:
      - appnet

  go-worker:
    build:
      context: ./go-worker
      dockerfile: ../docker/go-service/Dockerfile
    container_name: go-worker
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    networks:
      - appnet

  python-worker:
    build:
      context: ./python-worker
      dockerfile: ../docker/go-service/Dockerfile
    container_name: python-worker
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    networks:
      - appnet

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - appnet

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api-service
      - api-worker
      - go-worker
      - python-worker
    networks:
      - appnet

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - appnet

volumes:
  grafana-data:

networks:
  appnet:
    driver: bridge
