events {}

http {
    server {
        listen 80;

        # Публичный API
        location /api/ {
            proxy_pass http://api-service:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Служебные эндпоинты
        location /internal/ {
            allow 127.0.0.1;
            deny all;

            proxy_pass http://api-service:8080;
        }
    }
}
